spring:
    application:
        name: middle

backend:
    register:
        url: http://84.201.135.27:8080/v2/users
    create-account:
        url: http://84.201.135.27:8080/v2/users/{id}/accounts
    current-balance:
        url: http://84.201.135.27:8080/v2/users/{id}/accounts
    client-type: "http"

custom:
    timeout:
        connect: 5000
        read: 5000

server:
    port: 8081
